# Generated by Django 6.0.4 on 2026-04-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('word', models.CharField(max_length=200)),
                ('translation', models.CharField(blank=True, max_length=200)),
                ('found', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запрос пользователя',
                'verbose_name_plural': 'Запросы пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
